version: "3.8"

networks:
  laravel:
    driver: bridge

services:
  nginx_man:
    image: nginx:stable-alpine
    container_name: nginx_man
    ports:
      - "80:80" # Externo 8021, interno 80
    volumes:
      - .:/var/www/html:delegated
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_man
    restart: unless-stopped
    networks:
      - laravel

  php_man:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_man
    ports:
      - "9000:9000" # Externo 6000, interno 9000
    volumes:
      - ./php:/usr/local/etc/php
      - .:/var/www/html:delegated
    restart: unless-stopped
    networks:
      - laravel
